spectator:
  area: 10
tiers:
  "1":
    max_health: 15
    speed: 0.1
    resistance: -1
    strength: -1

  "2":
    max_health: 15
    speed: 0.1
    resistance: 0
    strength: -1

  "3":
    max_health: 10
    speed: 0.2
    resistance: 1
    strength: 0

  "4":
    max_health: 10
    speed: 0.2
    resistance: 1
    strength: 1

  "5":
    max_health: 5
    speed: 0.3
    resistance: 2
    strength: 1
