name: AlteredRespawn
version: '${version}'
main: world.anhgelus.msmp.alteredrespawn.AlteredRespawn
api-version: 1.19
author: ["MSMP", "Anhgelus Morhtuuzh", "Akik4"]
depend:
  - MSMPCore
  - kotlin-stdlib
